package:
  name: httpx
  version: 0.27.0
  top-level:
    - httpx
source:
  url: https://files.pythonhosted.org/packages/5c/2d/3da5bdf4408b8b2800061c339f240c1802f2e82d55e50bd39c5a881f47f0/httpx-0.27.0.tar.gz
  sha256: a0cb88a46f32dc874e04ee956e4c2764aba2aa228f650b06788ba6bda2962ab5
  patches:
    - patches/0001-Make-HttpStatusError-and-RequestError-pickleable.patch
requirements:
  run:
    - certifi
    - httpcore
    - anyio
    - idna
    - sniffio
about:
  home: ""
  PyPI: https://pypi.org/project/httpx
  summary: The next generation HTTP client.
  license: ""
extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
