package:
  name: sniffio
  version: 1.3.0
  top-level:
    - sniffio
source:
  url: https://files.pythonhosted.org/packages/c3/a0/5dba8ed157b0136607c7f2151db695885606968d1fae123dc3391e0cfdbf/sniffio-1.3.0-py3-none-any.whl
  sha256: eecefdce1e5bbfb7ad2eeaabf7c1eeb404d7757c379bd1f7e5cce9d8bf425384
about:
  home: https://github.com/python-trio/sniffio
  PyPI: https://pypi.org/project/sniffio
  summary: Sniff out which async library your code is running under
  license: MIT OR Apache-2.0
